
package tela;

import dao.AlunoDAO;
import dao.AulaDAO;
import entidade.Aluno;
import entidade.Aula;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class Chamada extends javax.swing.JDialog
{
    List<Aluno> lstAlunos = new ArrayList<Aluno>();
    Aula aula = null;
    Integer indexAtual = null;
    
    public Chamada(java.awt.Frame parent,Aula _aula)
    {
        super(parent, true);
        initComponents();
        
        aula = _aula;
        
        CarregaAlunos();
        ProximoAluno();
    }
    
    public void CarregaAlunos()
    {
        try
        {
            lstAlunos = new AlunoDAO().todosAlunos();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Erro:" + ex.getMessage());
        }
    }
    
    public void ProximoAluno()
    {
        indexAtual = (indexAtual == null ? 0 : indexAtual + 1);
        
        if(indexAtual < lstAlunos.size())
        {
            Aluno aluno = lstAlunos.get(indexAtual);

            lblAluno.setText(aluno.getNome());
            lblData.setText(new SimpleDateFormat("dd/MM/yyyy").format(this.aula.getDtAula()));
            lblDisciplina.setText(this.aula.getMateria().getMateria());
            lblQtdAluno.setText(Integer.toString((indexAtual + 1)) + "/" + Integer.toString(lstAlunos.size()));
        }
        else
        {
            FinalizaChamada();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        lblAluno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDisciplina = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        btnFalta = new javax.swing.JButton();
        btnPresente = new javax.swing.JButton();
        lblQtdAlunos = new javax.swing.JLabel();
        lblQtdAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Aluno:");

        lblAluno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAluno.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Disciplina:");

        lblDisciplina.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDisciplina.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Data da Aula:");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 51, 51));

        btnFalta.setBackground(new java.awt.Color(255, 0, 0));
        btnFalta.setText("FALTOU");
        btnFalta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFaltaActionPerformed(evt);
            }
        });

        btnPresente.setBackground(new java.awt.Color(51, 204, 0));
        btnPresente.setText("PRESENTE");
        btnPresente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPresenteActionPerformed(evt);
            }
        });

        lblQtdAluno.setText("0/0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblQtdAlunos)
                        .addGap(44, 44, 44)
                        .addComponent(lblQtdAluno)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblQtdAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtdAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPresenteActionPerformed
    {//GEN-HEADEREND:event_btnPresenteActionPerformed
       try
       {
           new AulaDAO().frequenciaAula(aula, lstAlunos.get(indexAtual), true);
           this.ProximoAluno();
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
       }
    }//GEN-LAST:event_btnPresenteActionPerformed

    public void FinalizaChamada()
    {
        JOptionPane.showMessageDialog(this, "Chamada Finalizada");
        this.dispose();
    }
    
    
    private void btnFaltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFaltaActionPerformed
    {//GEN-HEADEREND:event_btnFaltaActionPerformed
       try
       {
           new AulaDAO().frequenciaAula(aula, lstAlunos.get(indexAtual), false);
           this.ProximoAluno();
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
       }
    }//GEN-LAST:event_btnFaltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFalta;
    private javax.swing.JButton btnPresente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblQtdAluno;
    private javax.swing.JLabel lblQtdAlunos;
    // End of variables declaration//GEN-END:variables
}
